{% set name = "matplotlib-inline" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8423b23ec666be3d16e16b60bdd8ac4e86e840ebd1dd11a30b9f117f2fa0ab90

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - traitlets

test:
  imports:
    - matplotlib_inline
    - matplotlib_inline.backend_inline
  requires:
    - pip
    - matplotlib-base
    - ipython
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/ipython/matplotlib-inline
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Inline Matplotlib backend for Jupyter
  dev_url: https://github.com/ipython/matplotlib-inline

extra:
  recipe-maintainers:
    - Carreau
    - SylvainCorlay
    - martinRenou
    - fperez
